### ISSUE TITLE
{{URL}}/v1/users/login doens't work

### ISSUE THREAD

**Issue by ChiduVenkat** [fbsamples/WhatsApp-Business-API-Postman-Collection#1]
Am kind of facing issues in connecting to the docker container's url from postman upon calling the endpoint "https://localhost:9090/v1/users/login". 
Error in postman : "There was an error connecting to https://localhost:9090/v1/users/login. 
**Socket hang up**".

I followed all steps as mentioned in "Developer Setup: Single Instance" WhatsApp API. 
The docker containers "biz_waweb_1,biz_wacore_1 & biz_db_1" are up and running.
biz_waweb_1 runs on port "0.0.0.0:9090->443/tcp".

**Comment by mengyiyuan** [comment]
Hello,

Sorry but this is not an official support channel for WhatsApp Business API. :)

Could you please raise a direct support ticket instead? https://developers.facebook.com/docs/whatsapp/contact-support

Thank you!
