### ISSUE TITLE
URL in WhatsApp-Business-API-Postman-Collection 

### ISSUE THREAD

**Issue by surekha3079** [fbsamples/WhatsApp-Business-API-Postman-Collection#10]
Hi,

Iam using the WhatsApp-Business-API-Postman-Collection and  imported the collection in postman.
username and password is set based on document only.URL is mentioned to give **Webapp hostname**.
what should be the url??

**Comment by alanhhwong** [comment]
That is the URL to where you are hosting the webapp instance.  See installation details [here](https://developers.intern.facebook.com/docs/whatsapp/installation/dev-single-instance).

For further support, please use the Direct Support channel.
