### ISSUE TITLE
Unable to send media messages on 360dialog api 

### ISSUE THREAD

**Issue by maneul198** [fbsamples/WhatsApp-Business-API-Postman-Collection#22]
sorry for the bad english.

hi, now i am doing a few try to use 360 api https://waba.360dialog.io/ but i foundout problems with some types of messages like media messages,(sending messages by url), other messages types like simple text messages and media messages by Id works fine but no send media messages by url. Specifitly i get a 201 created response but i never get a message on my chat

thanks :);

**Comment by mengyiyuan** [comment]
Hi @maneul198, this would depend on each partner's integration, in this case 360Dialog. Could you please check with them regarding your questions? Thanks!
