### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by jhow2892** [fbsamples/WhatsApp-Business-API-Postman-Collection#5]
Good night people! I am now starting to send with the WhatsApp Business API and I am receiving this error ERR_CERT_AUTHORITY_INVALID, it seems to me that the SSL generated inside the docker is not valid, has anyone been through this?

**Comment by andrewlutz** [comment]
Hi, please submit a support ticket for your issue at https://business.facebook.com/direct-support.

Thanks
Andrew
