### ISSUE TITLE
preview_url not working

### ISSUE THREAD

**Issue by RaulGF92** [fbsamples/WhatsApp-Business-API-Postman-Collection#8]
Hi! I try made a preview_url with postman and isn't work, my body is:

```
{
  "to": "{{Recipient-WA-ID}}",
  "type": "text",
  "text": {
    "body": "https://www.marca.com/balonmano.html?intcmp=MENUMIGA&s_kw=balonmano"
  },
  "preview_url": true
}
```

with my whatapp's phone app and pc the preview works, but if i send like postman only show URL and not a preview URL.

**Comment by rafapastor** [comment]
@RaulGF92 in the end could you fix it?  how?

**Comment by andrewlutz** [comment]
Hi @rafapastor, please submit a support ticket at https://business.facebook.com/direct-support if you are experiencing an issue with the API.

Thanks
Andrew

**Comment by RaulGF92** [comment]
No Rafa, with postman or my Java Client library it has the same result. I think is a issue i hope they check.

**Comment by mengyiyuan** [comment]
Sorry for the late reply. To clarify:
URL previews are only rendered after one of the following has happened:
- The business has sent a message template to the user.
- The user initiates a conversation with a "click to chat" link.
- The user adds the business phone number to their address book and initiates a conversation.

This is documented in https://developers.facebook.com/docs/whatsapp/api/messages/text#urls, hope this helps!
